### PR TITLE
Java Programs #55 issue Solved

### PR DESCRIPTION
**Pull request by Nikhil-2002**

### CODE REVIEW

**Review by BimalRajGyawali — CHANGES_REQUESTED** [review]
Place the classes in appropriate packages.

**Comment by Nikhil-2002** [comment]
> Place the classes in appropriate packages.

sorry sir but I didn't get it actually I am beginner

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, there is a _package_ (folder) named _basics_. Place these classes there.

Also include the package info at top of each class as :
```java
package org.example.basics;
```
You can see other classes for references.

**Comment by BimalRajGyawali** [comment]
Also, you have 17 classes in your PR, which is very large. Include only 1 or 2 classes if possible. Thanks.

**Comment by Nikhil-2002** [comment]
> Also, you have 17 classes in your PR, which is very large. Include only 1 or 2 classes if possible. Thanks.

then can I set all class names same

**Comment by Nikhil-2002** [comment]
hey @BimalRajGyawali  please check all changes and accept PR

**Review by BimalRajGyawali — APPROVED** [review]

**Pull request merged**
