### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by panditsneha**
I have added the Implementation of OOPS in java. Kindly review and merge the code.

### CODE REVIEW

**Review by BimalRajGyawali — CHANGES_REQUESTED** [review]
Hi, there are various packages under _src/main/java/org/example/oop_. Please, add the classes in those appropriate packages. Thanks.

**Comment by panditsneha** [comment]
> Hi, there are various packages under _src/main/java/org/example/oop_. Please, add the classes in those appropriate packages. Thanks.

**Comment by panditsneha** [comment]
> Hi, there are various packages under _src/main/java/org/example/oop_. Please, add the classes in those appropriate packages. Thanks.

**Comment by panditsneha** [comment]
Sir, I have made the changes #100 .

**Pull request closed without merging**
