### PR TITLE
Added Stack and Queue folder

### PR DESCRIPTION
**Pull request by arorasukhmani**
I have added an implementation of stack using an array, LinkedList, and ArrayList. Infix to postfix and prefix conversion using stack. Reverse stack and push at the bottom. Implementation of queue using an array, LinkedList, 2 stack, and ArrayList. Circular queue and deque. Please review my pr add the hacktoberfest label.

### CODE REVIEW

**Review by BimalRajGyawali — COMMENTED** [review]
Hi, please use CamelCase(Every first letter of word capital) (not snake_case) for classnames.

Also, include smaller number of classes to ease the review process from next pr.

**Review by BimalRajGyawali — CHANGES_REQUESTED** [review]
use CamelCase(Every first letter of word capital) (not snake_case) for classnames

**Comment by arorasukhmani** [comment]
Yes, I'll change it

**Review by BimalRajGyawali — CHANGES_REQUESTED** [review]
Also, place the code under stack and queue package inside datastructures.

**Comment by arorasukhmani** [comment]
Okay, I'll do that

**Comment by arorasukhmani** [comment]
I made the respective changes.

**Review by BimalRajGyawali — APPROVED** [review]

**Pull request merged**
